### ISSUE TITLE
About Screen

### ISSUE THREAD

**Issue by raphir** [mvzdev/tripsterApp#1]
Activity erstellen, welche die

- Name
- Emailadressen

der Entwickler anzeigt. 

Activity erreichbar über die Actionbar => Menu

<img width="917" alt="Screenshot 2020-01-20 at 14 31 11" src="https://user-images.githubusercontent.com/19209321/72730439-aef7e600-3b91-11ea-899b-632e2d1aa007.png">

**Comment by raphir** [comment]
Icons in allen Grössen können direkt in Android Studio generiert werden!

==> drawable => new vector asset ==> clipArt

**Comment by mvzdev** [comment]
About screen implemented
